title: Welcome to my Blog
email: sergiu.moga@protonmail.com
description: >-
  This is where I usually post writeups to various CTF's/wargames
  I've played.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mogasergiu.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  mogasergiu

# Build settings
# theme: minima

theme: jekyll-theme-midnight
